<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <ItemGroup>
    <Antlr4 Include="Grammar\PathExpression.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>RuleTemplateEngine.Grammar</CustomToolNamespace>
      <Listener>false</Listener>
      <Visitor>true</Visitor>
    </Antlr4>
  </ItemGroup>

</Project>
